# -*- coding: utf-8 -*-
"""dicom to nifti.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zzd0EfEpullL-tklsdqlz_FDchoscUF9
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/rsna-miccai-brain-tumor-radiogenomic-classification



import dicom2nifti
import os
from glob import glob

#dicom2nifti.settings.disable_validate_sliceincrement()

#test_folder = '/home/nilgiri/Desktop/BraTS Challenge/rsna-miccai-brain-tumor-radiogenomic-classification/test/*'
train_folder = '/home/ravi/rsna-miccai-brain-tumor-radiogenomic-classification/train/*'

ritesh_test = '/home/ravi/rsna-miccai-brain-tumor-radiogenomic-classification/nifti_data/train'
mode = '0000'
for i in glob(train_folder):
  
  patient = i[-5:]
  #print(patient)
  a = train_folder + patient+'/*'
  b = train_folder[:-1] + patient
  for j in glob(a):
    #a = os.path.join(test_folder, str(i))
    j = j[75:]
    #j = j[15:]
    #print(j)
    if j == 'T1w':
      mode = '0001'
    elif j == 'T1wCE':
      mode = '0002'
    elif j == 'T2w':
      mode = '0003'
    elif j == 'FLAIR':
      mode = '0000'
    
    #print(j)
    input_path = os.path.join(b,j)
    print(input_path)
    dicom2nifti.dicom_series_to_nifti(input_path, os.path.join(ritesh_test,patient+'_'+mode+'.nii.gz'))
    except:
    	pass
